### ISSUE TITLE
Symlink Error Building Github Pages

### ISSUE THREAD

**Issue by kali-b** [nandomoreirame/dotX#1]
Hello,

I recently found your dotX template via the Jekyll themes website and wanted to use it for my personal site. However, whenever I try to use it (modified or copied straight from your repository) I get the following error emailed to me: 

"The page build failed with the following error:

A file was included in `source/index.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

If you have any questions you can contact us by replying to this email." 

The only include line is for the navbar.html, and when I serve using Jekyll the site works fine. It simply won't publish to my public domain name.

If you could shed any light as to why this might be occurring, it would be extremely helpful. 

Many thanks.

**Comment by Beansandboobiemilk** [comment]
I actually am getting this exact same error.  I was told by GitHub support that the _config.yml#L8 has a custom source directory. This was the explanation:  
While Jekyll by itself supports custom source directories, for security reasons we don't support them in Jekyll sites on GitHub Pages. This will get overridden with repository's top directory. So it's looking for ./_includes/... rather than ./source/_includes. You will need to reorganise the files into a standard Jekyll configuration.
Unfortunately, this is where I have remained stuck with the issue.  I am not familiar enough with Github to know specifically how to reorganize the files, so if anyone is able to provide insight there I would really appreciate it.

**Comment by KtorZ** [comment]
This means that you need to get rid of the `source` folder and move everything which is inside one stage above. Then, in the `_config.yml`, you'll need to remove the line `source: source`.
Also remove the `.travis.yml` and github should be able to build everything correctly for you.

**Comment by jokroese** [comment]
This is still an issue. I have come up with the same problem as reported here and in #20 . The suggestion above avoided the symlink problem but removed the CSS. Any thoughts on how to avoid this?
